package jframe;

import javax.swing.*;
import java.awt.*;
import java.awt.geom.*;

/**
 *
 * @author Angela
 * This program uses the methods included in the Graphics2D class to create a 
 * program that draws the following radiation hazard symbol
 */
public class RadiationSymbol extends javax.swing.JFrame {

    /**
     * Creates new form Radiation Symbol
     */
    public RadiationSymbol() {
        initComponents();
        this.setTitle("Radiation Symbol");
        setSize(500, 500);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setLocationRelativeTo(null);
        setVisible(true);

    }
    @Override
    public void paint(Graphics g) {
        // Repaints the frame and its components
        super.paint(g);
        // Declare and initialize a Graphics2D object
        Graphics2D circle = (Graphics2D) g;
        Graphics2D dot = (Graphics2D) g;
        Graphics2D arc1 = (Graphics2D) g;
        Graphics2D arc2 = (Graphics2D) g;
        Graphics2D arc3 = (Graphics2D) g;
        Graphics2D dot2 = (Graphics2D) g;
        circle.setStroke(new BasicStroke(10));
        circle.draw(new Ellipse2D.Double(100, 100, 300, 300));
        circle.setPaint(Color.YELLOW);
        circle.fill(new Ellipse2D.Double(100, 100, 300, 300));
        dot.setPaint(Color.BLACK);
        arc1.fillArc(110, 110, 280, 280, 0, 60);
        arc2.fillArc(110, 110, 280, 280, 120, 60);
        arc3.fillArc(110, 110, 280, 280, 240, 60);
        dot.setPaint(Color.YELLOW);
        dot.fill(new Ellipse2D.Double(225, 225, 50, 50));
        dot2.setPaint(Color.BLACK);
        dot2.fill(new Ellipse2D.Double(235, 235, 30, 30));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RadiationSymbol.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RadiationSymbol.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RadiationSymbol.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RadiationSymbol.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RadiationSymbol().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
