package jframe;

import javax.swing.*;
import java.awt.*;
import java.awt.geom.*;

/**
 *
 * @author Angela
 * This program uses the GradientPaint and Graphics2D classes to create
 * a program that draws a smiley interface.
 */
public class Smiley extends javax.swing.JFrame {

    /**
     * Creates new form Smiley
     */
    public Smiley() {
        initComponents();
        this.setTitle("Smiley");
        setSize(500, 500);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setLocationRelativeTo(null);
        setVisible(true);

    }
    @Override
    public void paint(Graphics g) {
        // Repaints the frame and its components
        super.paint(g);
        // Declare and initialize a Graphics2D object
        Graphics2D g2 = (Graphics2D) g;
        Graphics2D g3 = (Graphics2D) g;
        Graphics2D g4 = (Graphics2D) g;
        Graphics2D g5 = (Graphics2D) g;
        Graphics2D g6 = (Graphics2D) g;
        Graphics2D circle = (Graphics2D) g;
        
        Graphics2D eye1 = (Graphics2D) g;
        Graphics2D eye2 = (Graphics2D) g;
        Graphics2D arc1 = (Graphics2D) g;
        Graphics2D arc2 = (Graphics2D) g;
        Graphics2D arc3 = (Graphics2D) g;
        g2.setPaint(new GradientPaint(0, 0, Color.GREEN, 500, 500, Color.RED));
        
        g2.fill(new RoundRectangle2D.Double(0, 0, 100, 500, 500, 10));
        g3.fill(new RoundRectangle2D.Double(100, 0, 100, 500, 500, 10));
        g4.fill(new RoundRectangle2D.Double(200, 0, 100, 500, 500, 10));
        g5.fill(new RoundRectangle2D.Double(300, 0, 100, 500, 500, 10));
        g6.fill(new RoundRectangle2D.Double(400, 0, 100, 500, 500, 10));
        
        circle.setPaint(Color.BLACK);
        circle.setStroke(new BasicStroke(10));
        circle.draw(new Ellipse2D.Double(100, 100, 300, 300));
        circle.setPaint(Color.YELLOW);
        circle.fill(new Ellipse2D.Double(100, 100, 300, 300));
        
        eye1.draw(new Ellipse2D.Double(180, 200, 30, 50));
        eye1.setPaint(Color.BLACK);
        eye1.fill(new Ellipse2D.Double(180, 200, 30, 50));
        
        eye2.draw(new Ellipse2D.Double(300, 205, 20, 40));
        eye2.setPaint(Color.BLACK);
        eye2.fill(new Ellipse2D.Double(300, 205, 20, 40));
       
        arc1.draw(new Arc2D.Double(150, 150, 200, 200, 225, 90, Arc2D.OPEN)); 
        arc2.draw(new Arc2D.Double(110, 220, 100, 100, 270, 30, Arc2D.OPEN)); 
        arc3.draw(new Arc2D.Double(300, 230, 100, 100, 220, 30, Arc2D.OPEN)); 
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>                        

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RadiationSymbol.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RadiationSymbol.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RadiationSymbol.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RadiationSymbol.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Smiley().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    // End of variables declaration                   
}
